#!/bin/bash

if [ -e /lib/gentoo/functions.sh ]
then
    source /lib/gentoo/functions.sh
elif [ -e /etc/init.d/functions.sh ]
then
    source /etc/init.d/functions.sh
fi

check_exit()
{
    RETVAL=$?
    if [ $RETVAL -ne 0 ]
    then
        if [ "$1" -ne 0 ]
        then
            eerror "$2 failed"
            exit $RETVAL
        else
            ewarn "$2 failed"
        fi
    fi
}

want_update=$(emerge --pretend --oneshot sys-apps/portage)
if [[ $want_update =~ \[ebuild[^\]]+U[^\]]+\][[:space:]]+sys-apps\/portage ]]
then
	emerge --oneshot sys-apps/portage
	check_exit 1 "Updating portage"
fi

emerge --verbose --keep-going=y --usepkg=y --update --deep --changed-use --with-bdeps=y @world
check_exit 1 "Update"

emerge --depclean
check_exit 0 "Depclean"

eclean packages
check_exit 0 "Clean packages"
