#!/bin/bash

if [ -e /lib/gentoo/functions.sh ]
then
    source /lib/gentoo/functions.sh
elif [ -e /etc/init.d/functions.sh ]
then
    source /etc/init.d/functions.sh
fi

ebegin "emerge update"
emerge --keep-going=y --update --deep --changed-use --with-bdeps=y @world
eend $? "Update failed"

ebegin "emerge depclean"
emerge --depclean
eend $? "Depclean failed"

ebegin "eclean packages"
eclean packages
eend $? "Clean packages failed"
