#!/bin/bash

source /etc/init.d/functions.sh
source /etc/conf.d/gb-chroot

gb-mount m $1
RETVAL=$?
if [ $RETVAL -ne 0 ]
then
    echo "gb-mount m failed"
    exit $RETVAL
fi

if [ -z $2 ]
then
    einfo "Entering chroot $1"
    chroot $CHROOT_TOP/$1 /bin/bash
else
    einfo "Running in chroot $1:"
    einfo "'${@:2}'"
    chroot $CHROOT_TOP/$1 ${@:2}
fi

gb-mount u $1
RETVAL=$?
if [ $RETVAL -ne 0 ]
then
    echo "gb-mount u failed"
    exit $RETVAL
fi