#!/bin/bash

if [ -e /lib/gentoo/functions.sh ]
then
    source /lib/gentoo/functions.sh
elif [ -e /etc/init.d/functions.sh ]
then
    source /etc/init.d/functions.sh
fi

source /etc/conf.d/gb-chroot

EXIT_CODE=0

for i in $UPDATE_CHROOT
do
    gb-enter "$i" "${@:1}"

    RETVAL=$?
    if [ $RETVAL -ne 0 ]
        then
            eerror "$i failed"
            EXIT_CODE=$RETVAL
    fi    
done

exit $EXIT_CODE
