#!/bin/bash

if [ -e /lib/gentoo/functions.sh ]
then
    source /lib/gentoo/functions.sh
elif [ -e /etc/init.d/functions.sh ]
then
    source /etc/init.d/functions.sh
fi

source /etc/conf.d/gb-chroot

gb-mount m $1
RETVAL=$?
if [ $RETVAL -ne 0 ]
then
    eerror "Mounting chroot \"$1\" failed"
    exit $RETVAL
fi

if [ -z $2 ]
then
    einfo "Entering chroot $1"
    chroot $CHROOT_TOP/$1 /bin/bash --login
else
    einfo "Running in chroot $1:"
    einfo "'${@:2}'"
    chroot $CHROOT_TOP/$1 ${@:2}
fi

gb-mount u $1
RETVAL=$?
if [ $RETVAL -ne 0 ]
then
    eerror "Unmounting chroot \"$1\" failed"
    exit $RETVAL
fi