#!/bin/bash

if [ -e /lib/gentoo/functions.sh ]
then
    source /lib/gentoo/functions.sh
elif [ -e /etc/init.d/functions.sh ]
then
    source /etc/init.d/functions.sh
fi

check_exit()
{
    RETVAL=$?
    if [ $RETVAL -ne 0 ]
    then
        eerror "$1 failed"
        exit $RETVAL
    fi
}

EXIT_VALUE=0

source /etc/conf.d/gb-chroot

gb-mount m "$1"
check_exit "Mounting chroot \"$1\""

if [ -z "$2" ]
then
    einfo "Entering chroot $1"
    chroot "$CHROOT_TOP"/"$1" /bin/bash --login
    EXIT_VALUE=$?
else
    einfo "Running in chroot $1:"
    einfo "'${@:2}'"
    chroot "$CHROOT_TOP"/"$1" "${@:2}"
    EXIT_VALUE=$?
fi

gb-mount u "$1"
check_exit "Unmounting chroot \"$1\""

exit $EXIT_VALUE
