#!/bin/bash

if [ -e /lib/gentoo/functions.sh ]
then
    source /lib/gentoo/functions.sh
elif [ -e /etc/init.d/functions.sh ]
then
    source /etc/init.d/functions.sh
fi

source /etc/conf.d/gb-chroot

if [ -d "$CHROOT_TOP/$1" ]; then
    eerror "Chroot \"$1\" already exists."
    exit 1
fi

einfo "Creating $CHROOT_TOP/$1"
mkdir "$CHROOT_TOP"/"$1"

einfo "Creating /var/cache/binpkgs/$1"
(
    mkdir /var/cache/binpkgs/"$1"
)

#TODO implement downloading + gpg checking
ebegin "Unpacking $(ls "$CHROOT_TOP"/*"$2"-[0-9]*)"
(
    cd "$CHROOT_TOP"/"$1" || exit
    tar xpf "$CHROOT_TOP"/*"$2"-[0-9]* --xattrs-include='*.*' --numeric-owner
)
eend $?

if [ -n "$3" ]
then
    ROOT=$CHROOT_TOP/$1 emerge --usepkgonly --oneshot --nodeps app-emulation/qemu
    mkdir "$CHROOT_TOP"/"$1"/etc/portage/profile
    qlist -Iv|grep -E app-emulation/qemu >> "$CHROOT_TOP/$1/etc/portage/profile/package.provided"
fi

ebegin "Cleaning /dev"
(
    cd "$CHROOT_TOP"/"$1"/dev || exit
    rm -rf ./* .keep*
)
eend $?

einfo "Copying template make.conf"
(
    cp -pf /usr/share/gb-chroot/make.conf "$CHROOT_TOP"/"$1"/etc/portage
    cp -pf /usr/share/gb-chroot/make.conf.chroot "$CHROOT_TOP"/"$1"/etc/portage/make.conf.local
)

einfo "Creating repos.conf"
(
    mkdir "$CHROOT_TOP"/"$1"/etc/portage/repos.conf
)

einfo "Creating portage sets"
(
    mkdir "$CHROOT_TOP"/"$1"/etc/portage/sets
)

einfo "Copying resolv.conf"
(
    cp -pf --dereference /etc/resolv.conf "$CHROOT_TOP"/"$1"/etc/
)

einfo "Creating portage directories"
(
    mkdir "$CHROOT_TOP"/"$1"/var/db/repos/gentoo
    mkdir "$CHROOT_TOP"/"$1"/var/db/repos/crossdev
)

einfo "Creating layman directory"
(
    mkdir "$CHROOT_TOP"/"$1"/var/lib/layman
)

einfo "Updating /etc/profile"
(
    echo "PS1=\"($1) \${PS1}\"" >> "$CHROOT_TOP"/"$1"/etc/profile
)

einfo "Copying timezone information"
(
    cp -pf /etc/timezone /etc/localtime "$CHROOT_TOP"/"$1"/etc/
)

einfo "Copying /etc/locale.gen"
(
    cp -pf /etc/locale.gen "$CHROOT_TOP"/"$1"/etc/
)

ebegin "Generating locales"
(
    gb-enter "$1" locale-gen
)
eend $?

einfo "Copying misc /etc files"
(
    cp -pf /etc/passwd /etc/shadow /etc/group /etc/gshadow /etc/hosts \
    "$CHROOT_TOP"/"$1"/etc/
)

einfo "Dumping profile and locale"
(
    gb-enter "$1" eselect profile list
    gb-enter "$1" eselect locale list
)

ewarn "Don't forget to:"
ewarn "edit $CHROOT_TOP/$1/etc/portage/make.conf.local"
ewarn "select target's profile with:"
ewarn "'gb-enter $1 eselect profile'"
ewarn "select chroot's locale:"
ewarn "'gb-enter $1 eselect locale'"
ewarn "send /etc/portage from target into this chroot"
ewarn "or edit /etc/portage/* as required"
