#!/bin/bash

if [ -e /lib/gentoo/functions.sh ]
then
    source /lib/gentoo/functions.sh
elif [ -e /etc/init.d/functions.sh ]
then
    source /etc/init.d/functions.sh
fi

source /etc/conf.d/gb-chroot

check_exit()
{
    RETVAL=$?
    if [ $RETVAL -ne 0 ]
    then
        if [ "$1" -ne 0 ]
        then
            eerror "$2 failed"
            exit $RETVAL
        else
            ewarn "$2 failed"
        fi
    fi
}

rc-service rsyncd stop

emerge --sync
check_exit 1 "Sync"

emerge --noreplace --oneshot sys-apps/portage
check_exit 1 "Updating host's portage"

emerge --verbose --keep-going=y --update --deep --changed-use --with-bdeps=y @world
check_exit 1 "Host update"

emerge --depclean --exclude="$DEPCLEAN_EXCLUDE"
check_exit 0 "Host depclean"

gb-all gb-update-chroot
ALL_RETVAL=$?

eclean distfiles
check_exit 0 "Host distfiles"

if [ $ALL_RETVAL -ne 0 ]
    then
        eerror "gb-all failed, not starting rsyncd"
    else
        rc-service rsyncd start
fi
