#!/bin/bash

if [ -e /lib/gentoo/functions.sh ]
then
    source /lib/gentoo/functions.sh
elif [ -e /etc/init.d/functions.sh ]
then
    source /etc/init.d/functions.sh
fi

check_exit()
{
    RETVAL=$?
    if [ $RETVAL -ne 0 ]
    then
        if [ "$1" -ne 0 ]
        then
            eerror "$2 failed"
            exit $RETVAL
        else
            ewarn "$2 failed"
        fi
    fi
}

if [ "$(eselect news count)" != "0" ]
then
    eselect news read
fi

rc-service rsyncd stop

emerge --sync
check_exit 1 "Sync"

emerge --verbose --keep-going=y --update --deep --changed-use --with-bdeps=y @world
check_exit 1 "Host update"

emerge --depclean --exclude="sys-kernel/linux-image"
check_exit 0 "Host depclean"

gb-all gb-update-chroot

eclean distfiles
check_exit 0 "Host distfiles"

rc-service rsyncd start
