#!/bin/bash

if [ -e /lib/gentoo/functions.sh ]
then
    source /lib/gentoo/functions.sh
elif [ -e /etc/init.d/functions.sh ]
then
    source /etc/init.d/functions.sh
fi

rc-service rsyncd stop

ebegin "emerge --sync"
emerge --sync > /dev/null
eend $? "Sync failed"

ebegin "emerge update"
emerge --keep-going=y --update --deep --changed-use --with-bdeps=y @world
eend $? "Host update failed"

ebegin "emerge depclean"
emerge --depclean --exclude="sys-kernel/linux-image"
eend $? "Host depclean failed"

gb-all gb-update-chroot

ebegin "eclean distfiles"
eclean distfiles
eend $? "Host distfiles failed"

rc-service rsyncd start